Add BlobHash to Go binding
Fantom-foundation/evmc pull request #1
Opened 2024-06-20 15:25 UTC by facuMH

This PR adds:
- passage of blobhash slice in `getTxContext`
- function  `evmcBytes32_ptr` which casts from a `[]hash` to `*C.evmc_bytes32`
- pins the memory for the buffer in the transaction context before calling `C.step_n_wrapper` so that it can be accessed safely from the C runtime and it won't be moved or deleted by Go's garbage collector.

2024-06-24 18:17 UTC, HerbertJordan requested changes
I think this looks good and should be backward compatible. Nice job.

Please extend the modifications to also include the `Execute` function for regular contract executions.

2024-06-24 18:17 UTC, HerbertJordan commented on bindings/go/evmc/evmc.go
> +func evmcBytes32_ptr(in []Hash) *C.evmc_bytes32 {
Since it is only used in the `host.go` file, this function should be moved there.

2024-06-24 18:17 UTC, HerbertJordan commented on bindings/go/evmc/evmc.go
> +	}()
nit: this should be the same as
```suggestion
	defer pnr.Unpin()
```

2024-06-24 18:17 UTC, HerbertJordan commented on bindings/go/evmc/evmc.go
> +	pnr := new(runtime.Pinner)
The pinning of the blob hash array should also be done in the `Execute` function above, to get support for blob hashes also in the regular case, not running the StepN function.

2024-06-24 18:17 UTC, HerbertJordan commented on bindings/go/evmc/evmc.go
> +	pnr := new(runtime.Pinner)
The `runtime.Pinner` type only got added in go 1.21. This should be reflected by updating the minimum Go version in the `go.mod` file of this project.

2024-06-24 18:34 UTC, HerbertJordan commented on bindings/go/evmc/evmc.go
> +	}()
The pinning should be skipped if the BlobHashes are empty. Otherwise the access to element 0 fails.

2024-06-25 11:46 UTC, LuisPH3 commented
mentioned here: https://github.com/Fantom-foundation/Tosca/pull/548#pullrequestreview-2138429904

2024-06-25 19:18 UTC, HerbertJordan requested changes

2024-06-25 19:18 UTC, HerbertJordan commented on bindings/go/evmc/evmc.go
> +	}
I think this block needs to be in both, the `Execute` and the `StepN` function.

2024-06-27 18:34 UTC, HerbertJordan approved these changes

2024-06-28 07:00 UTC, merged